DockerCI {
    fileName = "Dockerfile"
    imageSourceName = "alpine"
    imageSourceTag = "latest"
    maintainer = "Condoamanti Condoamanti@gmail.com"
    update = true
    upgrade = true
    packages = ["curl"]
    environmentVariables = []
    additionalCommands = [
        "curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.19.0/bin/linux/amd64/kubectl",
        "chmod +x ./kubectl",
        "mv ./kubectl /usr/local/bin/kubectl"
    ]
    entryPoint = ["/usr/local/bin/kubectl"]
    imageDestinationRepositoryUrl = "docker.io"
    // Can be any of the following
    // - docker.io
    // - artifactory.jittersolutions.com
    imageDestinationName = "condoamanti/alpine-kubectl"
    // Can be any of the following
    // - condoamanati/*
    // - "docker-local/*"
    imageDestinationTag = "latest"
}