DockerCI {
    fileName = "Dockerfile"
    imageSourceName = "alpine"
    imageSourceTag = "latest"
    maintainer = "Condoamanti Condoamanti@gmail.com"
    update = true
    upgrade = true
    packages = ["git", "make", "go"]
    environmentVariables = ["GOROOT /usr/lib/go", "GOPATH /go", "PATH /go/bin:\$PATH"]
    imageDestinationName = "k8snode1dc1.jittersolutions.com:32382/docker-local/alpine"
    // Can be any of the following
    // - condoamanati/*
    // - "k8snode1dc1.jittersolutions.com:32382/docker-local/*"
    imageDestinationTag = "golang"
    imageDestinationRepositoryUrl = "k8snode1dc1.jittersolutions.com:32382"
    // Can be any of the following
    // - docker.io
    // - k8snode1dc1.jittersolutions.com:32382
}