DockerCI {
    fileName = "Dockerfile"
    imageSourceName = "alpine"
    imageSourceTag = "latest"
    maintainer = "Condoamanti Condoamanti@gmail.com"
    update = true
    upgrade = true
    packages = ["git", "make", "go"]
    environmentVariables = ["GOROOT /usr/lib/go", "GOPATH /go", "PATH /go/bin:\$PATH"]
    additionalCommands = ["mkdir -p \${GOPATH}/src \${GOPATH}/bin"]
    imageDestinationRepositoryUrl = "artifactory.jittersolutions.com"
    // Can be any of the following
    // - docker.io
    // - artifactory.jittersolutions.com
    imageDestinationName = "docker-local/alpine-golang"
    // Can be any of the following
    // - condoamanati/*
    // - "docker-local/*"
    //imageDestinationTag = "golang"

}