DockerCI {
    fileName = "Dockerfile"
    imageSourceName = "alpine"
    imageSourceTag = "latest"
    maintainer = "Condoamanti Condoamanti@gmail.com"
    update = true
    upgrade = true
    packages = ["curl", "git", "make", "go"]
    environmentVariables = ["GOROOT /usr/lib/go", "GOPATH /go", "PATH /go/bin:\$PATH", "JFROG_CLI_OFFER_CONFIG false"]
    additionalCommands = [
        "mkdir -p \${GOPATH}/src \${GOPATH}/bin",
        "/usr/bin/curl -fLs https://api.bintray.com/content/jfrog/jfrog-cli-go/\\\$latest/jfrog-cli-linux-amd64/jfrog?bt_package=jfrog-cli-linux-amd64 -o /usr/bin/jfrog",
        "chmod u+x /usr/bin/jfrog"
    ]
    imageDestinationRepositoryUrl = "artifactory.jittersolutions.com"
    // Can be any of the following
    // - docker.io
    // - artifactory.jittersolutions.com
    imageDestinationName = "docker-local/alpine-golang"
    // Can be any of the following
    // - condoamanati/*
    // - "docker-local/*"
    imageDestinationTag = "latest"
}