DockerCI {
    fileName = "Dockerfile"
    imageSourceName = "alpine"
    imageSourceTag = "3.12.0"
    maintainer = "Condoamanti Condoamanti@gmail.com"
    update = true
    upgrade = false
    packages = ["epel-release", "golang", "git"]
    imageDestinationName = "k8snode1dc1.jittersolutions.com:32382/docker-local/centos"
    // Can be any of the following
    // - condoamanati/*
    // - "k8snode1dc1.jittersolutions.com:32382/docker-local/*"
    imageDestinationTag = "centos7"
    imageDestinationRepositoryUrl = "k8snode1dc1.jittersolutions.com:32382"
    // Can be any of the following
    // - docker.io
    // - k8snode1dc1.jittersolutions.com:32382
}