DockerCI {
    fileName = "Dockerfile"
    imageSourceName = "centos"
    imageSourceTag = "centos7"
    maintainer = "Condoamanti Condoamanti@gmail.com"
    update = true
    upgrade = false
    packages = ["epel-release", "golang", "git"]
    imageDestinationName = "condoamanti/test"
    imageDestinationTag = "centos7"
    imageDestinationRepositoryUrl = "docker.io"
}