DockerCI {
    fileName = "Dockerfile"
    imageName = "centos"
    imageTag = "centos7"
    maintainer = "Condoamanti Condoamanti@gmail.com"
    update = true
    upgrade = false
    packages = ["epel-release", "golang", "git"]
}