DockerCI {
    fileName = "Dockerfile"
    imageSourceName = "centos"
    imageSourceTag = "centos7"
    maintainer = "Condoamanti Condoamanti@gmail.com"
    update = true
    upgrade = false
    packages = ["golang", "git"]
    imageDestinationName = "condoamanti"
    imageDestinationTag = "centos7"
    imageDestinationRepositoryName = "test"
    imageDestinationRepositoryUrl = "docker.io"
}